var word_acro_data = {
  "&": "and",
  "w\/": "with",
  "ab": "air base",
  "a\/c": "aircraft",
  "acft": "aircraft",
  "add'l": "additional",
  "ad": "active duty",
  "adet": "national security agency associate directorate of education and training",
  "adpe": "automated data processing equipment",
  "adsc": "active duty service commitment",
  "aef": "air expeditionary force",
  "aeg": "air expeditionary group",
  "af": "air force",
  "afam": "air force achievement medal",
  "afb": "air force base",
  "afcaf": "air force central adjudication facility",
  "afcm": "air force commendation medal",
  "afco": "air force cryptologic office",
  "affor": "air force forces",
  "afh": "air force handbook",
  "afi": "air force instruction",
  "afit": "air force institute of technology",
  "afm": "air force manual",
  "afoqt": "air force officer qualifying test",
  "afosi": "air force office of special investigation",
  "afotec": "air force test and evaluation center",
  "afpc": "air force personnel center",
  "afrc": "air force reserve command",
  "afres": "air force reserve",
  "afrotc": "air force reserve officer training corps",
  "afs": "air force station",
  "afsc": "air force specialty code",
  "afto": "air force technical order",
  "als": "airman leadership school",
  "amu": "aircraft maintenance unit",
  "amxs": "aircraft maintenance squadron",
  "ang": "air national guard",
  "aor": "area of responsibility",
  "apz": "above the promotion zone",
  "arb": "air reserve base",
  "asap": "as soon as possible",
  "at\/fp": "antiterrorism\/force protection",
  "ato": "air tasking order",
  "attn": "attention",
  "aw": "airlift wing",
  "awacs": "airborne warning and control system",
  "awc": "army war college",
  "awd": "award",
  "awol": "absent without leave",
  "ba": "bachelor of arts",
  "acad": "academy",
  "accom": "accompany",
  "accomp": "accomplish",
  "acct": "account",
  "add\u2019l": "additional",
  "admin": "administrate",
  "adv": "advancement",
  "agcy": "agency",
  "ack": "acknowledge",
  "afld": "airfield",
  "amn": "airman",
  "alpha": "alphabetical",
  "alt": "alternate",
  "ammo": "ammunition",
  "appt": "appointment",
  "appr": "approve",
  "approx": "approximate",
  "asses": "assessment",
  "assoc": "associate",
  "assn": "association",
  "asgn": "assignment",
  "asst": "assistant",
  "auth": "authorize",
  "auto": "automatic",
  "aux": "auxiliary",
  "avail": "availability",
  "avg": "average",
  "awd'd": "award",
  "blvd": "boulevard",
  "brig gen (usaf)": "brigadier general",
  "bldg": "building",
  "bus": "business",
  "capt": "captain",
  "cat": "category",
  "ctr": "center",
  "cert": "certification",
  "chg": "change",
  "chrg": "charge",
  "chrono": "chronological",
  "civ": "civilian",
  "col": "colonel",
  "cmbt": "cbt",
  "cmd": "command",
  "cc": "commander",
  "cmdr": "cc",
  "cdr": "cmdr",
  "comm": "communications",
  "conf": "conference",
  "config": "configuration",
  "contr": "contractor",
  "ctrl": "control",
  "coop": "cooperate",
  "coord": "coordination",
  "corp": "corporate",
  "crs": "course",
  "crses": "courses",
  "cust": "customer",
  "dec": "decoration",
  "def": "defense",
  "deg": "degree",
  "del": "delete",
  "dep": "deployed",
  "dod": "department of defense",
  "dev": "development",
  "dist": "distribution",
  "dir": "directorate",
  "div": "division",
  "doc": "documentation",
  "dup": "duplicate",
  "ea": "each",
  "educ": "education",
  "elig": "eligible",
  "elim": "eliminate",
  "emerg": "emergency",
  "eng": "english",
  "enl": "enlisted",
  "equip": "equipment",
  "equiv": "equivalent",
  "est": "estimate",
  "etc": "etcetera",
  "evac": "evacuation",
  "eval": "evaluation",
  "exam": "examination",
  "exch": "exchange",
  "exec": "executive",
  "ex": "exercise",
  "exer": "ex",
  "exped": "expedite",
  "fam": "family",
  "fav": "favorable",
  "feb": "february",
  "fed": "federal",
  "fld": "field",
  "fig": "figure",
  "1st lt": "first lieutenant",
  "fy10": "fiscal year 2010",
  "fit": "fitness",
  "flt": "flight",
  "flt pln": "flight plan",
  "fwd": "forward",
  "fraud": "fraudulent",
  "freq": "frequent",
  "fri": "friday",
  "gen": "general",
  "govt": "government",
  "gpa": "grade point average",
  "grad": "graduate",
  "gnd": "ground",
  "grp": "gp",
  "gp": "group",
  "guar": "guarantee",
  "hq": "headquarters",
  "ht": "height",
  "hs": "high school",
  "hwy": "highway",
  "hist": "history",
  "hon": "honorable",
  "hosp": "hospital",
  "hrs": "hours",
  "ident": "identification",
  "id": "ident",
  "immed": "immediate",
  "immune": "immunization",
  "inc": "incorporate",
  "incr": "increase",
  "indef": "indefinite",
  "indep": "independent",
  "indiv": "individual",
  "indoc": "indoctrinate",
  "info": "information",
  "inop": "inoperative",
  "insp": "inspector",
  "instr": "instructor",
  "intel": "intelligence",
  "intl": "international",
  "intro": "introduction",
  "jt": "joint",
  "jul": "july",
  "jun": "june",
  "jr.": "junior",
  "lab": "laboratory",
  "lat": "latitude",
  "ldr": "leader",
  "lvl": "level",
  "lib": "liberate",
  "lt": "lieutenant",
  "lt gen": "lieutenant general",
  "liq": "liquid",
  "mag": "magazine",
  "maint": "maintenance",
  "mx": "maintenance",
  "maj": "major",
  "mng": "manage",
  "mgt": "management",
  "mgmt": "management",
  "mar": "march",
  "max": "maximum",
  "mech": "mechanical",
  "med": "medicine",
  "mtg": "meeting",
  "mbr": "member",
  "mbrshp": "membership",
  "memo": "memorandum",
  "mil": "military",
  "min": "minimum",
  "misc": "miscellaneous",
  "msn": "mission",
  "mob": "mobilize",
  "mod": "modification",
  "mon": "monday",
  "mo": "month",
  "mos": "months",
  "natl": "national",
  "neg": "negative",
  "norm": "normal",
  "n\/a": "not applicable",
  "nov": "november",
  "#": "number",
  "no.": "#",
  "obj": "object",
  "oct": "october",
  "ofcr": "officer",
  "ops": "operations",
  "oppor": "opportunity",
  "org": "organization",
  "orig": "original",
  "pkg": "package",
  "pg": "page",
  "para": "paragraph",
  "pt": "patient",
  "perm": "permanent",
  "pers": "personnel",
  "psnl": "pers",
  "phys": "physical",
  "pop": "population",
  "pref": "preference",
  "prelim": "preliminary",
  "prep": "prepare",
  "pres": "president",
  "rx": "prescription",
  "prev": "previous",
  "prim": "primary",
  "priv": "private",
  "prob": "problem",
  "prof": "professor",
  "pgm": "program",
  "prgm": "pgm",
  "proj": "project",
  "promo": "promotion",
  "pos": "position",
  "psych": "psychology",
  "pub": "publication",
  "qual": "quality",
  "qty": "quantity",
  "qt": "quart",
  "qtr": "quarter",
  "qtrly": "quarterly",
  "rdy": "ready",
  "recv": "receive",
  "rec": "recommendation",
  "recon": "reconnaissance",
  "recog": "recognize",
  "rcds": "records",
  "reg": "regulation",
  "reorg": "reorganize",
  "rep": "represent",
  "req": "request",
  "res": "residence",
  "resrv": "reserve",
  "resp": "respon",
  "respon": "responsible",
  "ret": "retired",
  "rtn": "return",
  "rqmts": "requirements",
  "rte": "route",
  "rwy": "runway",
  "sat": "saturday",
  "sched": "schedule",
  "sci": "science",
  "srch": "search",
  "sec": "second",
  "sel": "selection",
  "sem": "semester",
  "sr": "senior",
  "sep": "september",
  "seq": "sequence",
  "svc": "service",
  "sig": "signature",
  "sit": "situation",
  "spec": "specify",
  "sq": "squadron",
  "sqdn": "sq",
  "std": "standard",
  "stan\/eval": "standardization and evaluation",
  "stat": "statistic",
  "strat": "strategy",
  "subj": "subject",
  "subor": "subordinate",
  "subpara": "subparagraph",
  "sub": "substitute",
  "sun": "sunday",
  "supv": "supervisor",
  "supp": "supplement",
  "spt": "support",
  "surg": "surgical",
  "srvy": "survey",
  "synch": "synchronize",
  "sym": "symbol",
  "sys": "system",
  "tm": "team",
  "tech": "technical",
  "telecom": "telecommunications",
  "tel": "tele",
  "tele": "telephone",
  "telecon": "telephone conference",
  "temp": "temporary",
  "term": "terminate",
  "termin": "termination",
  "thou": "thousand",
  "k": "thou",
  "thurs": "thursday",
  "tot": "total",
  "trad": "traditional",
  "tng": "trng",
  "trng": "training",
  "trans": "transportation",
  "tx": "treatment",
  "tues": "tuesday",
  "unclas": "unclassified",
  "unfav": "unfavorable",
  "univ": "university",
  "unk": "unknown",
  "vax": "vaccination",
  "veh": "vehicle",
  "vert": "vertical",
  "vs": "versus",
  "vet": "veteran",
  "vp": "vice president",
  "vis": "visual",
  "vol": "volunteer",
  "wpn": "weapon",
  "wx": "weather",
  "wk": "week",
  "wt": "weight",
  "wg": "wing",
  "wkshp": "workshop",
  "yr": "year",
  "\/year": "per year",
  "brfg": "briefing",
  "cbt": "combat",
  "coord'd": "coordinated",
  "dept": "department",
  "gov't": "government",
  "ir": "infrared",
  "log": "logistics",
  "med sys": "medical services",
  "mgr": "manager",
  "msg": "message",
  "nat'l": "national",
  "op": "operation",
  "pax": "passengers",
  "prsnl": "personnel",
  "rm": "room",
  "rqmt": "requirement",
  "schd": "schedule",
  "sen": "senator",
  "sim": "simulator",
  "stu": "student",
  "vs.": "versus"
}
