var word_acro_data = {
    "&amp;": ["and"],
    "w/": ["with"],
    "ab": ["air base"],
    "a/c": ["aircraft"],
    "acft": ["aircraft"],
    "add'l": ["additional"],
    "ad": ["active duty"],
    "adet": ["national security agency associate directorate of education and training"],
    "adpe": ["automated data processing equipment"],
    "adsc": ["active duty service commitment"],
    "aef": ["air expeditionary force"],
    "aeg": ["air expeditionary group"],
    "af": ["air force"],
    "afam": ["air force achievement medal"],
    "afb": ["air force base"],
    "afcaf": ["air force central adjudication facility"],
    "afcm": ["air force commendation medal"],
    "afco": ["air force cryptologic office"],
    "affor": ["air force forces"],
    "afh": ["air force handbook"],
    "afi": ["air force instruction"],
    "afit": ["air force institute of technology"],
    "afm": ["air force manual"],
    "afoqt": ["air force officer qualifying test"],
    "afosi": ["air force office of special investigation"],
    "afotec": ["air force test and evaluation center"],
    "afpc": ["air force personnel center"],
    "afrc": ["air force reserve command"],
    "afres": ["air force reserve"],
    "afrotc": ["air force reserve officer training corps"],
    "afs": ["air force station"],
    "afsc": ["air force specialty code"],
    "afto": ["air force technical order"],
    "als": ["airman leadership school"],
    "amu": ["aircraft maintenance unit"],
    "amxs": ["aircraft maintenance squadron"],
    "ang": ["air national guard"],
    "aor": ["area of responsibility"],
    "apz": ["above the promotion zone"],
    "arb": ["air reserve base"],
    "asap": ["as soon as possible"],
    "at/fp": ["antiterrorism/force protection"],
    "ato": ["air tasking order"],
    "attn": ["attention"],
    "aw": ["airlift wing"],
    "awacs": ["airborne warning and control system"],
    "awc": ["army war college"],
    "awd": ["award", "awards"],
    "awd": ["awards", "award"],
    "awol": ["absent without leave"],
    "ba": ["bachelor of arts"],
    "acad": ["academy"],
    "accom": ["accompany", "accommodate","accomodation", "accompanied"],
    "accomp": ["accomplish"],
    "acct": ["account"],
    "add’l": ["additional"],
    "admin": ["administrate"],
    "adv": ["advancement"],
    "agcy": ["agency"],
    "ack": ["acknowledge"],
    "afld": ["airfield", "airfields"],
    "aflds": ["airfield", "airfields"],
    "amn": ["airman"],
    "alpha": ["alphabetical"],
    "alt": ["alternate"],
    "ammo": ["ammunition"],
    "appt": ["appointment", "appointments"],
    "appts":["appointment", "appointments"],
    "appr": ["approve", "approval"],
    "approx": ["approximate"],
    "asses": ["assessment"],
    "assoc": ["associate"],
    "assn": ["association"],
    "asgn": ["assignment"],
    "asst": ["assist","assistant"],
    "auth": ["authorize"],
    "auto": ["automatic"],
    "aux": ["auxiliary"],
    "avail": ["availability"],
    "avg": ["average"],
    "blvd": ["boulevard"],
    "brig gen": ["brigadier general"],
    "bldg": ["building", "buildings"],
    "blds": ["buildings", "buildings"],
    "bus": ["business"],
    "capt": ["captain"],
    "cat": ["category"],
    "ctr": ["center"],
    "cert": ["certification"],
    "chg": ["change"],
    "chrg": ["charge"],
    "chrono": ["chronological"],
    "civ": ["civilian"],
    "col": ["colonel"],
    "cmbt": ["cbt"],
    "cmd": ["command"],
    "cc": ["commander"],
    "cmdr": ["cc"],
    "cdr": ["cmdr"],
    "comm": ["communications"],
    "conf": ["conference"],
    "config": ["configuration"],
    "contr": ["contractor", "contract"],
    "ctrl": ["control"],
    "coop": ["cooperate"],
    "coord": ["coordination"],
    "corp": ["corporate", "corporation"],
    "crs": ["course", "courses"],
    "crses": ["courses"],
    "cust": ["customer"],
    "dec": ["decoration"],
    "def": ["defense"],
    "deg": ["degree"],
    "del": ["delete"],
    "dep": ["deployed"],
    "dod": ["department of defense"],
    "dev": ["develop", "development"],
    "dev'd": ["develop", "developed"],
    "dist": ["distribution"],
    "dir": ["directorate"],
    "div": ["division"],
    "doc": ["documentation"],
    "dup": ["duplicate"],
    "ea": ["each"],
    "educ": ["educate", "education"],
    "elig": ["eligible"],
    "elim": ["eliminate"],
    "emerg": ["emergency"],
    "eng": ["english"],
    "enl": ["enlisted"],
    "equip": ["equipment"],
    "equiv": ["equivalent"],
    "est": ["estimate"],
    "etc": ["etcetera"],
    "evac": ["evacuation"],
    "eval": ["evaluation"],
    "exam": ["examination"],
    "exch": ["exchange"],
    "exec": ["executive"],
    "ex": ["exercise"],
    "exer": ["ex"],
    "exped": ["expedite"],
    "fam": ["family", "families"],
    "fams":["family", "families"],
    "fav": ["favorable"],
    "feb": ["february"],
    "fed": ["federal"],
    "fld": ["field"],
    "fig": ["figure", "figures"],
    "figs": ["figure", "figures"],
    "1st lt": ["first lieutenant"],
    "fy10": ["fiscal year 2010"],
    "fit": ["fitness"],
    "flt": ["flight", "flights"],
    "flts": ["flight", "flights"],
    "fwd": ["forward"],
    "fraud": ["fraudulent"],
    "freq": ["frequent"],
    "fri": ["friday"],
    "gen": ["general"],
    "govt": ["government"],
    "gpa": ["grade point average"],
    "grad": ["graduate"],
    "gnd": ["ground"],
    "grp": ["group", "gp"],
    "grps": ["groups", "group", "gps"],
    "gp": ["group", "grp"],
    "gps": ["groups"],
    "guar": ["guarantee"],
    "hq": ["headquarters"],
    "ht": ["height"],
    "hs": ["high school"],
    "hwy": ["highway"],
    "hist": ["history"],
    "hon": ["honorable"],
    "hosp": ["hospital"],
    "hr": ["hour", "hours"],
    "hrs": ["hour", "hours"],
    "ident": ["identification"],
    "id": ["ident"],
    "immed": ["immediate"],
    "immune": ["immunization"],
    "inc": ["incorporate"],
    "incr": ["increase"],
    "indef": ["indefinite"],
    "indep": ["independent"],
    "indiv": ["individual"],
    "indoc": ["indoctrinate"],
    "info": ["information"],
    "inop": ["inoperative"],
    "insp": ["inspector"],
    "instr": ["instructor"],
    "instrs": ["instructors"],
    "intel": ["intelligence"],
    "intl": ["international"],
    "intro": ["introduction"],
    "jt": ["joint"],
    "jul": ["july"],
    "jun": ["june"],
    "jr.": ["junior"],
    "lab": ["laboratory"],
    "lat": ["latitude"],
    "ldr": ["leaders", "leader"],
    "ldrs": ["leaders", "leader"],
    "lvl": ["level"],
    "lib": ["liberate"],
    "lt": ["lieutenant"],
    "lt gen": ["lieutenant general"],
    "liq": ["liquid"],
    "mag": ["magazine", "magazines"],
    "mags": ["magazine", "magazines"],
    "maint": ["maintenance"],
    "mx": ["maintenance"],
    "maj": ["major"],
    "mng": ["manage"],
    "mgt": ["management"],
    "mgmt": ["management"],
    "mar": ["march"],
    "max": ["maximum"],
    "mech": ["mechanical"],
    "med": ["medicine"],
    "mtg": ["meeting", "meetings"],
    "mtgs": ["meeting", "meetings"],
    "mbr": ["member", "members"],
    "mbrs":["member", "members"],
    "mbrshp": ["membership"],
    "memo": ["memorandum"],
    "mil": ["military"],
    "min": ["minimum"],
    "misc": ["miscellaneous"],
    "msn": ["mission", "missions"],
    "msns":["mission", "missions"],
    "mob": ["mobilize"],
    "mod": ["modification", "modifications"],
    "mods": ["modification", "modifications"],
    "mon": ["monday"],
    "mo": ["month", "months"],
    "mos": ["month", "months"],
    "natl": ["national"],
    "neg": ["negative"],
    "norm": ["normal"],
    "n/a": ["not applicable"],
    "nov": ["november"],
    "#": ["number"],
    "no.": ["#", "number"],
    "obj": ["object", "objects"],
    "objs": ["object", "objects"],
    "oct": ["october"],
    "ofcr": ["officer", "officers"],
    "ofcrs": ["officer", "officers"],
    "ops": ["operations"],
    "oppor": ["opportunity"],
    "org": ["organization"],
    "orig": ["original"],
    "pkg": ["package","packages"],
    "pkgs": ["package","packages"],
    "pg": ["page"],
    "para": ["paragraph"],
    "pt": ["patient"],
    "perm": ["permanent"],
    "pers": ["personnel"],
    "psnl": ["pers"],
    "phys": ["physical"],
    "pln": ["plan"],
    "pop": ["population"],
    "pref": ["preference"],
    "prelim": ["preliminary"],
    "prep": ["prepare"],
    "pres": ["president"],
    "rx": ["prescription"],
    "prev": ["previous"],
    "prim": ["primary"],
    "priv": ["private"],
    "prob": ["problem", "problems"],
    "probs": ["problem", "problems"],
    "prof": ["professor", "professors"],
    "profs": ["professor", "professors"],
    "pgm": ["program", "programs"],
    "prgm":["program", "programs"],
    "pgms":["program", "programs"],
    "prgms":["program", "programs"],
    "proj": ["project", "projects"],
    "projs": ["project","projects"],
    "promo": ["promotion", "promotions"],
    "promos": ["promotion", "promotions"],
    "pos": ["position"],
    "psych": ["psychology"],
    "pub": ["publication"],
    "qual": ["quality"],
    "qty": ["quantity"],
    "qt": ["quart"],
    "qtr": ["quarter"],
    "qtrly": ["quarterly"],
    "rdy": ["ready"],
    "recv": ["receive"],
    "rec": ["recommendation"],
    "recon": ["reconnaissance"],
    "recog": ["recognize"],
    "rcd": ["record", "records"],
    "rcds": ["record", "records"],
    "reg": ["regulation"],
    "reorg": ["reorganize"],
    "rep": ["represent"],
    "req": ["request"],
    "res": ["residence"],
    "resrv": ["reserve"],
    "resp": ["respon"],
    "respon": ["responsible"],
    "ret": ["retired"],
    "rtn": ["return"],
    "rqmts": ["requirements"],
    "rte": ["route"],
    "rwy": ["runway"],
    "sat": ["saturday"],
    "sched": ["schedule"],
    "sci": ["science"],
    "srch": ["search"],
    "sec": ["second"],
    "sel": ["selection"],
    "sem": ["semester"],
    "sr": ["senior"],
    "sep": ["september"],
    "seq": ["sequence"],
    "svc": ["service"],
    "sig": ["signature"],
    "sit": ["situation"],
    "spec": ["specify"],
    "sq": ["squadron", "squadrons", "sqdn", "sqdns"],    
    "sqdn": ["sq", "sqs", "squadron", "squadrons"],
    "sqs":["squadron", "squadrons", "sqdn", "sqdns"],
    "sqdns":["sq", "sqs", "squadron", "squadrons"],
    "std": ["standard"],
    "stan/eval": ["standardization and evaluation"],
    "stat": ["statistic", "statistics"],
    "stats":["statistic", "statistics"],
    "strat": ["strategy"],
    "subj": ["subject"],
    "subor": ["subordinate"],
    "subpara": ["subparagraph"],
    "sub": ["substitute"],
    "sun": ["sunday"],
    "supv": ["supervisor"],
    "supp": ["supplement"],
    "spt": ["support"],
    "surg": ["surgical"],
    "srvy": ["survey"],
    "synch": ["synchronize"],
    "sym": ["symbol"],
    "sys": ["system"],
    "tm": ["team", "tms"],
    "tms": ["team", "tms"],
    "tech": ["technical"],
    "telecom": ["telecommunications"],
    "tel": ["tele"],
    "tele": ["telephone"],
    "telecon": ["telephone conference"],
    "temp": ["temporary"],
    "term": ["terminate"],
    "termin": ["termination"],
    "thou": ["thousand"],
    "k": ["thou"],
    "thurs": ["thursday"],
    "tot": ["total"],
    "trad": ["traditional"],
    "tng": ["trng", "training", "train"],
    "trng": ["training", "train", "tng"],
    "trans": ["transportation"],
    "tx": ["treatment"],
    "tues": ["tuesday"],
    "unclas": ["unclassified"],
    "unfav": ["unfavorable"],
    "univ": ["university"],
    "unk": ["unknown"],
    "vax": ["vaccination"],
    "veh": ["vehicle"],
    "vert": ["vertical"],
    "vs": ["versus"],
    "vet": ["veteran", "veterans"],
    "vets":["veteran","veterans"],
    "vp": ["vice president"],
    "vis": ["visual"],
    "vol": ["volunteer", "volunteers"],
    "vols": ["volunteer", "volunteers"],
    "wpn": ["weapon","weapons"],
    "wpns": ["weapon", "weapons"],
    "wx": ["weather"],
    "wk": ["week", "weeks"],
    "wks":["week", "weeks"],
    "wt": ["weight"],
    "wg": ["wing", "wings"],
    "wgs":["wing", "wings"],
    "wkshp": ["workshop", "workshops"],
    "wkshps": ["workshop", "workshops"],
    "yr": ["year", "years"],
    "yrs" :["year", "years"],
    "/year": ["per year"],
    "brfg": ["briefing", "breifings"],
    "brfgs": ["briefing", "breifings"],
    "cbt": ["combat"],
    "coord'd": ["coordinated"],
    "dept": ["department"],
    "gov't": ["government"],
    "ir": ["infrared"],
    "log": ["logistics"],
    "med sys": ["medical services"],
    "mgr": ["manager", "managers"],
    "mgrs":["manager", "managers"],
    "msg": ["message"],
    "msgs": ["message", "messages"],
    "nat'l": ["national"],
    "op": ["operation"],
    "pax": ["passengers"],
    "prsnl": ["personnel"],
    "rm": ["room", "rooms"],
    "rms": ["room", "rooms"],
    "rqmt": ["requirement", "requirements"],
    "rqmts": ["requirement", "requirements"],
    "schd": ["schedule"],
    "sen": ["senator"],
    "sim": ["simulator"],
    "stu": ["student"],
    "vs.": ["versus"]
}
